package io.webagent4j.action;

/** Ordered audit stages emitted by an action pipeline. */
public enum ActionStage {
    ACTION_STARTED,
    TARGET_RESOLUTION_STARTED,
    TARGET_RESOLVED,
    PRECONDITION_STARTED,
    PRECONDITION_COMPLETED,
    BACKEND_ACTION_STARTED,
    BACKEND_ACTION_COMPLETED,
    STABILIZATION_STARTED,
    STABILIZATION_COMPLETED,
    VERIFICATION_STARTED,
    VERIFICATION_COMPLETED,
    ACTION_COMPLETED,
    ACTION_FAILED
}
