package io.webagent4j.recording;

import java.util.Objects;

/**
 * Stable, caller-supplied identifier for one {@link WorkflowRecording}.
 *
 * <p>Like {@code WorkflowId}, a recording's identity is never generated by this module: the caller
 * chooses an explicit value (for example a run ID from their own orchestration system) so the same
 * physical recording always carries the same identity. {@link WorkflowReplayVerifier} deliberately
 * never compares this field - it is trace metadata, not part of a recording's semantic content. The
 * value is persisted verbatim and may appear in JSON, {@code toString()}, and logs; callers must
 * not place secrets or other sensitive data in it.
 *
 * @param value the non-blank, non-sensitive identifier text
 */
public record RecordingId(String value) {

    /** Validates that {@code value} is non-null and non-blank. */
    public RecordingId {
        Objects.requireNonNull(value, "value");
        if (value.isBlank()) {
            throw new IllegalArgumentException("value cannot be blank");
        }
    }

    /** Returns the raw identifier text. */
    @Override
    public String toString() {
        return value;
    }
}
