package io.webagent4j.plugin;

/** Stable categories for fail-closed plugin discovery failures. */
public enum PluginLoadFailureType {
    SERVICE_CONFIGURATION_ERROR,
    PROVIDER_INSTANTIATION_FAILED,
    PROVIDER_DESCRIPTOR_FAILED,
    INVALID_PLUGIN_DESCRIPTOR,
    DUPLICATE_PLUGIN_ID,
    PROVIDER_STRATEGY_DISCOVERY_FAILED,
    INVALID_LOCATOR_STRATEGY,
    DUPLICATE_LOCATOR_STRATEGY_ID
}
