package io.webagent4j.locator.api;

/** Semantic roles supported by the deterministic locator and observation APIs. */
public enum ElementRole {
    LINK,
    BUTTON,
    TEXTBOX,
    SEARCHBOX,
    CHECKBOX,
    RADIO,
    SELECT,
    OPTION,
    SLIDER,
    SPINBUTTON,
    SWITCH,
    HEADING,
    FORM,
    TABLE,
    LIST,
    IMAGE,
    BANNER,
    NAVIGATION,
    MAIN,
    SEARCH,
    REGION,
    COMPLEMENTARY,
    CONTENTINFO,
    DIALOG,
    ALERTDIALOG,
    ALERT,
    STATUS,
    MENU,
    MENUBAR,
    MENUITEM,
    TAB,
    TABLIST,
    TABPANEL,
    GRID,
    UNKNOWN
}
